"""
Weather Reporter - Conditionals and Simple Loops Exercise
Generated by Copilot
"""

from typing import List, Union

Number = Union[int, float]

# TODO: Return a label based on the Celsius temperature
# "freezing" (<=0), "cold" (1-10), "mild" (11-20), "warm" (21-30), "hot" (>30)
def temperature_feel(temp_c: Number) -> str:
    if temp_c <= 0:
        return "freezing"
    elif 1 <= temp_c <= 10:
        return "cold"
    elif 11 <= temp_c <= 20:
        return "mild"
    elif 21 <= temp_c <= 30:
        return "warm"
    elif temp_c > 30:
        return "hot"


# TODO: Count how many entries equal "rainy" (case-insensitive)
# Ignore other values like "sunny", "cloudy", etc.
def count_rainy_days(forecast: List[str]) -> int:
    
    count = 0
    for i in forecast:
        if not str.lower(i) == "rainy":
            continue
        count += 1
    return count


# TODO: Return index of the first day with temperature strictly above 20
# If none, return -1
def first_warm_day(temps: List[Number]) -> int:
    for i in temps:
        if i > 20:
            return temps.index(i)
    return -1


# TODO: Keep a running total from numbers without exceeding limit
# Stop adding when the next number would push the total above limit
# Return the total that does not exceed limit
def sum_until_limit(numbers: List[Number], limit: Number) -> Number:
    total = 0
    for i in numbers:
        if total + i > limit:
            return total
        total += i

feel = temperature_feel(5)
count = count_rainy_days(["Sunny", "Rainy", "RAINY"]) 
first = first_warm_day([10, 20, 22, 19])
sumVar = sum_until_limit([4, 4, 10], 9)

print(feel)
print(count)
print(first)
print(sumVar)