"""
Coffee Shop Order - Variables and Data Types Exercise
Generated by Copilot
"""

# TODO: Create a variable for the customer's name (string)
customer_name = "Adam"

# TODO: Create a variable for the drink size (string: "small", "medium", or "large")
drink_size = "large"

# TODO: Create a variable for the quantity of drinks ordered (integer)
quantity = 1

# TODO: Create a variable for the price per drink (float)
price_per_drink = 3.80

# TODO: Calculate the total price before discount, 
total_price = quantity * price_per_drink

# TODO: Create a variable for loyalty membership status (boolean)
is_loyalty_member = True

# TODO: Use if to calculate the discount amount (0.0 if not a member, or 10% of total_price if member)

if is_loyalty_member:
    discount_amount = 0.10
else:
    discount_amount = 0.00

# TODO: Calculate the final price after discount (total_price - discount_amount)
final_price = total_price - discount_amount